[SPC-cluster]
text = '''
A cluster is simply a collection of nodes (some of them probably bridges) that
all have the same `cluster_uid` and each node has a unique `node_uid`.
'''

[SPC-node]
text = '''
A node is a device with a `node_uid`, `cluster_uid` and registered `fn_id`s
that can communicate on one or more networks.

It participates in the cluster by declaring functions. Functions are just a
`fn_id` associated with a routine which performs an entire RPC when it is
executed using `CALL_FN`.

The declared functions can be called by any other node on the network by
specifying the `exec_uid` of the executor and their own node_uid as
`init_uid`. The initiator node also specifies `[cx_id, input_data, dropable,
stream]`.

# Network Startup
- the node broadcasts `FN_BROADCAST_NODE` (it continues to do this over an application
  specific period)
- bridges reply with `FN_REGISTER_BRIDGE`. The node will store (typically)
  between 2-5 of these bridges.
- other nodes on the cluster can now use the node as an executor of functions
  using `CALL_FN`.
'''
